# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9806fc9718600ef05422a2e2157060b78cac303b7b64da0f6906014c292ca21822adb0ce647357e1d87bfec665266aaa423707c6be62511b3bc47b61cca9a355

test:
  secret_key_base: 3a03e508a035824fcaf48704cfce41488ebdb4b8be2f32b8fce74ddd633149e788e24f1730c8e3e0bff6be223393d14ec8a86299e57930ac1822247ebc1443e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
